---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - apt::default
  - name: centos-7.1
    run_list:
      - yum-epel::default
  - name: windows-server-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard

suites:
  - name: languages_rust
    run_list: languages_rust::default
  - name: languages_rust_prefix
    run_list: languages_rust::prefix
