sudo: required

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - master

services:
  - docker

env:
  matrix:
    - CHEF_VERSION=12.1.0 LANGUAGE=erlang OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=node OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=ruby OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=rust OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=erlang OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=node OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=ruby OS=ubuntu-1404
    - CHEF_VERSION=latest LANGUAGE=rust OS=ubuntu-1404
    - CHEF_VERSION=12.1.0 LANGUAGE=erlang OS=centos-7
    - CHEF_VERSION=12.1.0 LANGUAGE=node OS=centos-7
    - CHEF_VERSION=12.1.0 LANGUAGE=ruby OS=centos-7
    - CHEF_VERSION=12.1.0 LANGUAGE=rust OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=erlang OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=node OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=ruby OS=centos-7
    - CHEF_VERSION=latest LANGUAGE=rust OS=centos-7

matrix:
  fast_finish: true

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  # We have to install chef-sugar for ChefSpec
  - /opt/chefdk/bin/chef gem install chef-sugar
  # Ensure kitchen-docker is available for testing
  - /opt/chefdk/bin/chef gem install kitchen-docker
script:
  - /opt/chefdk/bin/chef --version
  - /opt/chefdk/bin/cookstyle --version
  - /opt/chefdk/bin/cookstyle
  - /opt/chefdk/bin/foodcritic --version
  - /opt/chefdk/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/rspec spec
  - /opt/chefdk/bin/kitchen --version
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml travis_wait 45 /opt/chefdk/bin/kitchen verify "languages-$LANGUAGE-$OS"
